### ISSUE TITLE
The path '..../EventScope/onos-infoflow/onos-infoflow/bin' does not exist.

### ISSUE THREAD

**Issue by lsiddiqsunny** [bujcich/EventScope#1]
I was trying to run ONOS event flow graph generator. After running
`mvn clean install`

I could see that the build is successful. But when running:
`java -jar target/onos-infoflow-0.0.1-SNAPSHOT.jar`

I got these errors:
`Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '..../EventScope/onos-infoflow/onos-infoflow/bin' does not exist.
        at soot.SourceLocator.getClassSourceType(SourceLocator.java:288)
        at soot.SourceLocator.lookupInClassPath(SourceLocator.java:565)
        at soot.asm.AsmClassProvider.find(AsmClassProvider.java:36)
        at soot.SourceLocator.getClassSource(SourceLocator.java:173)
        at soot.Scene.tryLoadClass(Scene.java:820)
        at soot.Scene.loadBasicClasses(Scene.java:1504)
        at soot.Scene.loadNecessaryClasses(Scene.java:1587)
        at edu.illinois.perform.onosif.ONOSInfoFlowManager.main(ONOSInfoFlowManager.java:109)

Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Error: The path '...../EventScope/onos-infoflow/onos-infoflow/bin' does not exist.
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:143)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2352)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2324)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
        at soot.SourceLocator.getClassSourceType(SourceLocator.java:286)
        ... 7 more

Caused by: java.lang.Exception: Error: The path ..../EventScope/onos-infoflow/onos-infoflow/bin' does not exist.
        at soot.SourceLocator$1.load(SourceLocator.java:67)
        at soot.SourceLocator$1.load(SourceLocator.java:62)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        ... 13 more`

Would you please tell me a way around?

**Comment by rebeccagmgm** [comment]
me too, and I don't know how to fix it
